<?xml version="1.0" encoding="UTF-8"?>
<!-- Created by EADS DS - IPCC -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://weblab-project.org/services/contentprovider"
	xmlns:contentprovider="http://weblab-project.org/services/contentprovider"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://weblab-project.org/services/contentprovider"
	name="ContentProvider">

	<import
		namespace="http://weblab-project.org/services/contentprovider"
		location="../interfaces/ContentProvider.wsdl" />

	<service name="ContentProvider">
		<documentation>
			A sample content provider service.
		</documentation>
		<port name="ContentproviderPort"
			binding="contentprovider:ContentProviderSOAPBinding">
			<soap:address location="" />
		</port>
	</service>

</definitions>