<?xml version="1.0" encoding="UTF-8"?>
<!-- Created by EADS DS - IPCC -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://services.weblab.eads.com/fulltextsearching"
	xmlns:searcher="http://services.weblab.eads.com/searcher"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://services.weblab.eads.com/fulltextsearching"
	name="FullTextSearchingService">
	<import namespace="http://services.weblab.eads.com/searcher"
		location="../interfaces/Searcher.wsdl">
	</import>
	
	<service name="FullTextSearchingService">
		<port name="SearcherPort"
			binding="searcher:SearcherSOAPBinding">
			<soap:address location=""></soap:address>
		</port>
	</service>
</definitions>
